### ISSUE TITLE
Error with JWT - TypeError: token.split is not a function

### ISSUE THREAD

**Issue by jairoerazobotero** [scg-unibe-ch/ese2019-team10#2]
This error appears when i login (The login is successful):

core.js:6014 ERROR Error: Uncaught (in promise): TypeError: token.split is not a function
TypeError: token.split is not a function
    at JwtHelperService.push../node_modules/@auth0/angular-jwt/src/jwthelper.service.js.JwtHelperService.decodeToken (jwthelper.service.js:70)

**Comment by BenjaminBlaesi** [comment]
there was a variable name mismatch between frontend and backend, should be fixed now but please test
